name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    name: Rust 1.61.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.61.0
      - run: cargo test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.61.0
        with:
          components: clippy
      - run: cargo clippy -- --no-deps -Dclippy::all
      - run: cargo clippy --tests -- --no-deps -Dclippy::all
      - run: cargo clippy --examples -- --no-deps -Dclippy::all

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.61.0
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
      - run: rustfmt --check tests/**/*.rs
