name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    name: Rust 1.56.0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.56.0
      - run: cargo test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.56.0
        with:
          components: clippy
      - run: cargo clippy -- -Dclippy::all
      - run: cargo clippy --tests -- -Dclippy::all
      - run: cargo clippy --examples -- -Dclippy::all

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@1.56.0
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
      - run: rustfmt --check tests/**/*.rs
