name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    name: Rust 1.56.0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.56.0
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy -- -Dclippy::all
      - run: cargo clippy --tests -- -Dclippy::all
      - run: cargo clippy --examples -- -Dclippy::all

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.56.0
          override: true
          profile: minimal
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Format tests
        run: rustfmt --check tests/**/*.rs
